### ISSUE TITLE
"Cannot inline bytecode" error since 1.42

### ISSUE THREAD

**Issue by BoD** [MarkusAmshove/Kluent#133]
I've seen this problem referenced [here](https://github.com/MarkusAmshove/Kluent/issues/75#issuecomment-425492203), and marked as resolved, but unfortunately it's still present in our project.

We were using 1.31 for the longest time, and today we're upgrading a few dependencies including Kluent.  I tried the latest (1.47) and I got this compilation error:
```
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
```

I then tried to go back versions until one works, and the latest that doesn't have this issue for us is 1.41.

Ideas?

**Comment by BoD** [comment]
Sorry I forgot to mention it's an Android project.

**Comment by MarkusAmshove** [comment]
This looks like a big regression.

I'm not that experienced with Android, but I thought it can target Java8 Bytecode now, since it also works with Java8 language features?

**Comment by MarkusAmshove** [comment]
[1.42](https://github.com/MarkusAmshove/Kluent/commit/7de53542f9efa84bf2c994aa461689b9138d178e#diff-c197962302397baf3a4cc36463dce5ea) set the jvm target for Android to 1.6

**Comment by BoD** [comment]
I am sorry I spoke too early.  Actually, the latest version that works with our project is 1.39 (not 1.42).
I can confirm that we don't have the issue with 1.38, but we do have it with 1.39.

**Comment by MarkusAmshove** [comment]
Is your project some "special" kind of old project? With special I mean old Android API or something like this?
I can use the newest Kluent version in new Android projects.

**Comment by BoD** [comment]
Hmm not really. We have a minSdk 16 / targetSdk 28 / compileSdk 28.
I should also mention that all the lines that show this error contain either `mock<SomeClass>()` or `any()`

**Comment by MarkusAmshove** [comment]
Do you have a hard dependency on `mockito-kotlin`? Kluent will introduce a transitive dependency to version `1.5.0` into your project

**Comment by BoD** [comment]
Actually yes we do have our own dependency to `mockito-kotlin` and exclude the transitive one from kluent, like this:

```
    testImplementation 'com.nhaarman:mockito-kotlin-kt1.1:1.5.0'
    testImplementation("org.amshove.kluent:kluent:$kluentVersion") {
        exclude group: 'com.nhaarman', module: 'mockito-kotlin-kt1.1'
    }
    testImplementation("org.amshove.kluent:kluent-android:$kluentVersion") {
        exclude group: 'com.nhaarman', module: 'mockito-kotlin-kt1.1'
    }
``` 

Is this wrong?

**Comment by BoD** [comment]
Thanks a lot for your help :)

I've tried to remove the explicit dependency to `com.nhaarman:mockito-kotlin-kt1.1` and `org.amshove.kluent:kluent` so I'm left with only this:

```
testImplementation("org.amshove.kluent:kluent-android:$kluentVersion")
```

But now for some reason we have unresolved references on a few methods, the ones that have spaces in it: `should be equal to`, `should be`, `it returns`, etc.  Ideas? :) .  Once again, thanks for your support and patience.

**Comment by MarkusAmshove** [comment]
Oh I see :smile:

The only reason why there is a `kluent-android` artifact is because Android doesn't support the backtick methods (methods with spaces in the name).
I'm actually curious how you ran tests that way :-)

I can't find the actual JetBrains documentation where this is stated at the moment, but found [this](https://discuss.kotlinlang.org/t/android-issue-with-backticked-method-names/66/5) which might explain why they ran.

If you're not using the Android-tests (which fall under `instrumentation` I think) you can replace

`org.amshove.kluent:kluent-android`
with
`org.amshove.kluent:kluent`

again and it should work :-)

**Comment by BoD** [comment]
Thanks for the clarification.  Indeed actually, currently we're only using Kluent for unit tests (so they're actually running on the JVM, not on an Android device).

So now I have tried this:
```
    testImplementation("org.amshove.kluent:kluent:$kluentVersion") {
        exclude group: 'com.nhaarman.mockitokotlin2', module: 'mockito-kotlin'
    }
```

and I still have the "inline bytecode" compilation errors

**Comment by MarkusAmshove** [comment]
By the way the packages are the same.

So simply replacing 

``should be``
with
`shouldBe`

will do the trick and also replace the imports correctly

**Comment by BoD** [comment]
Thanks again, I think we're almost there :)

By using this:
```
testImplementation 'com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0'
testImplementation "org.amshove.kluent:kluent-android:$kluentVersion"
```

and removing all spaced, it still doesn't work but for a completely different reason:

```
java.lang.NoClassDefFoundError: kotlin/test/AssertionsKt
```

I suppose we need a "Kotlin test" dependency, but not familiar with this. - Ideas?

**Comment by MarkusAmshove** [comment]
Strange, this is supposed to also be resolved transitive, at least the POM of `1.47` states the dependency.

the lib in question would be

`testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlinVersion` 
(replace with your kotlin version)

**Comment by MarkusAmshove** [comment]
This is the POM of 1.47:

```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.amshove.kluent</groupId>
  <artifactId>kluent-android</artifactId>
  <version>1.47</version>
  <dependencies>
    <dependency>
      <groupId>org.amshove.kluent</groupId>
      <artifactId>kluent-common</artifactId>
      <version>1.47</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.3.10</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-reflect</artifactId>
      <version>1.3.10</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-test</artifactId>
      <version>1.3.10</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.nhaarman.mockitokotlin2</groupId>
      <artifactId>mockito-kotlin</artifactId>
      <version>2.0.0</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

Maybe I did something wrong with `runtime` vs `compile` scope? I'll have a look at that

**Comment by MarkusAmshove** [comment]
Glad that it works for you  :-)
I'll keep this issue open go remind me to look into the runtime stuff, it might need to be changed

**Comment by BoD** [comment]
Just FYI, I just got a new similar issue, when trying to use `should`: 

`kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath`

**Comment by MarkusAmshove** [comment]
I think I've managed to resolve the issue.

Can you try and confirm with
```testImplementation 'org.amshove.kluent:kluent-android:1.48'```
?

**Comment by ychescale9** [comment]
@MarkusAmshove just curious how you fix this with the `kluent-android` artifact as there's no change log yet?
Also currently `kluent` and `kluent-android` versions are out of sync. Is this temporary or are they going to be published separately with their own versions going forward?

**Comment by MarkusAmshove** [comment]
Yss it is a temporary release for android only, just to confirm that it works for you.

But I'll push the changes today and also bump the version for other platforms to get in sync again.

It feels like a hacky solution, but I guess it has to be this way until AS fixes it on their side.
The dependencies are now declared twice for android, as `implementation` and `runtime` :shrug:

**Comment by ychescale9** [comment]
Sorry I meant to comment on https://github.com/MarkusAmshove/Kluent/issues/130

I see. I found out that this only happens when the gradle project does NOT references a pure Kotlin only project :joy:

**This works:**
```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
}
...
dependencies {
    implementation project(path: ':kotlin-module') // here
    testImplementation "org.amshove.kluent:kluent:${versions.kluent}"
}
```

**This doesn't:**
```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
}
...
dependencies {
    implementation project(path: ':android-module') // here
    testImplementation "org.amshove.kluent:kluent:${versions.kluent}"
}
```

**`kotlin-module/build.gradle`:**
```
plugins {
    id 'kotlin'
}
...
dependencies {
    ...
}
```

**`android-module/build.gradle`:**
```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
}
...
dependencies {
    ...
}
```

**Comment by MarkusAmshove** [comment]
Closing this issue, as it is resolved in 1.48
